### ISSUE TITLE
上架至 chrome 線上應用程式商店

### ISSUE THREAD

**Issue by dannnyliang** [sovmedcare/hackthon-pixnet#16]
# Description
[Chrome 線上應用程式商店](https://chrome.google.com/webstore/category/extensions?hl=zh-TW)
增加完成度，並且只需要提供商店連結，就能給主辦單位使用

# Note
此為非必要項目

**Comment by jackypan1989** [comment]
1. 已付費 150 元
2. 已上架審核中
